server:
  port: 8080
spring:
  application:
    name: messaging-example
  actor:
    node-port: 9090
    boss-threads: 1
    worker-threads: 4
    node-white-list: 909.*
    monitor-enable: true
    enable-sync: true
    actor-class-name: com.lockdown.messaging.example.actor.SpringActor
    actor-codec-class-name: com.lockdown.messaging.example.actor.SimpleStringCodec
    actor-port: 8081
    master:
      address: 127.0.0.1
      port: 9090
  data:
    mongodb:
      uri: mongodb://localhost:27017
      #authentication-database: admin
      database: actor


