server:
  port: 8083
spring:
  application:
    name: messaging-example
  actor:
    node-port: 9090
    actor-port: 8082
    boss-threads: 1
    worker-threads: 4
    node-white-list: 909.*
    monitor-enable: true
    enable-sync: true
    actor-class-name: com.lockdown.messaging.example.actor.SpringActor
    actor-message-codec-class-name:
  data:
    mongodb:
      uri: mongodb://actorRoot:actorRoot@139.199.57.133:27017
      authentication-database: admin
      database: actor


